export const NEW_CHARACTER_FORM_MODAL = 'NEW_CHARACTER_FORM_MODAL';
export const NEW_CHARACTER_FORM = 'NEW_CHARACTER_FORM';
export const EDIT_CHARACTER_FORM_MODAL = 'EDIT_CHARACTER_FORM_MODAL';
export const EDIT_CHARACTER_FORM = 'EDIT_CHARACTER_FORM';
